#!/usr/bin/env node
// Runs as prebuild / prestart to stamp src/version.js with today's build date.
// Version format: YYYY.M.D (matching existing package.json convention)

const fs = require("fs")
const path = require("path")

const now = new Date()
const year = now.getFullYear()
const month = now.getMonth() + 1
const day = now.getDate()

const version = `${year}.${month}.${day}`
const buildDate = `${year}-${String(month).padStart(2, "0")}-${String(day).padStart(2, "0")}`

// Update src/version.js
const versionFile = path.join(__dirname, "..", "src", "version.js")
fs.writeFileSync(
  versionFile,
  `// Auto-generated by scripts/update-version.js — do not edit manually\nexport const VERSION = '${version}';\nexport const BUILD_DATE = '${buildDate}';\n`,
  "utf8"
)

// Keep package.json in sync
const pkgPath = path.join(__dirname, "..", "package.json")
const pkg = JSON.parse(fs.readFileSync(pkgPath, "utf8"))
pkg.version = version
fs.writeFileSync(pkgPath, JSON.stringify(pkg, null, 2) + "\n", "utf8")

console.log(`[update-version] v${version} (${buildDate})`)
